version: '3.8'

services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
        ports:
            - 5434:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
