TENDERS_DIR = r"C:/Users/misa5/Desktop/500/tenderhack/back/chatapp/tenders/"
INPUT_FILENAME = r"./docx_files/contract.docx"
LOCATIONS = {
    'finance_source': "1",
    'contractor_address': "Часть 2",
    'supplier': "Преамбула",
    'document_name': "1",
    'contractor_oktmo': "11",
    'ikz': "1",
    'reciver': "11",
    'prepay': "2",
    'contractor_kpp': "11",
    'contractor_okpo': "11",
    'price': "2",
    'place': "Преамбула",
    'supplier_signer_in': "11",
    'contractor_inn': "11",
    'contractor_ogrn': "11",
    'contract_date': "Преамбула",
    'contractor': "Преамбула",
    'supplier_email': "11",
    'supplier_ogrn': "11",
    'period': "3",
    'supplier_kpp': "11",
    'supplier_bik': "11",
    'contactor_bank': "11",
    'contractor_bik': "11",
    'contractor_email': "11",
    'contractor_okato': "11",
    'contractor_bank_k_account': "11",
    'supplier_inn': "11",
    'today': "Преамбула",
    'supplier_signer': "Преамбула",
    'contractor_signer': "Преамбула",
    'price_str': "2",
    'contractor_signer_in': "11",
    'supplier_address': "11",
    'contractorr_phone': "11",
    'contract_n': "Преамбула",
    'supplier_bank': "11",
    'supplier_phone': "11",
    'supplier_bank_k_account': "11"
}
EMAIL = "loot500chat@mail.ru"
EMAIL_PWD = "FErtaiGSR6jUcGaEn5sn"
EMAIL_RECIPIENT = "gcd248@mail.ru"
